"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-04-09 13:58:04.470805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('migrasfreeCid', sa.String(), nullable=False),
    sa.Column('usuarioGrafico', sa.String(), nullable=False),
    sa.Column('verificacionEquipos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resumen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('reports_migrasfreeCid_idx', 'reports', ['migrasfreeCid'], unique=False)
    op.create_index('reports_timestamp_idx', 'reports', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('reports_timestamp_idx', table_name='reports')
    op.drop_index('reports_migrasfreeCid_idx', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
